clc;
clear all;
disp('CALCULATION OF INDUCTANCE AND CAPACI TANCE OF 3 PHASE UNSYMMETRI C LINE - TRANSPOSED' );
d=input('Enter diameter in cm:');
r=d/2;
rad=r*10^(-2);
Dab=input(' Enter distance between conductors A & B in m: ');
Dbc=input(' Enter distance between conductors B & C in m:');
Dca=input('Enter distance between conductors C & A in m:');
f=input(' Enter Frequency');
Deq=(Dab*Dbc*Dca)^(1/3);
r1=rad*0.7788;
L=2*10^(-7)*log(Deq/r1);
C=(2*pi*8.854*10^(-12))/(log(Deq/rad));
disp('INDUCTANCE(in H/m):');
disp(L);
disp('CAPACITANCE(in F/m):');
disp(C);
XL=2*pi*f*L;
XC=1/(2*pi*f*C);
disp('INDUCTIVER REACTANCE(in ohm/m):'); 
disp(XL);
disp('CAPACITIVE REACTANCE(in ohm/m):');
disp(XC);
